### ISSUE TITLE
Setup problem, very new on unix

### ISSUE THREAD

**Issue by c4sti3l** [dillbyrne/es-cec-input#10]
Hello,
first of all, sorry for my english ^^.

I've tried to run es-cec-input .
At first i've installed cec-utils with

`sudo apt-get install cec-utils`

No problems.

After this i've tried to install python-uinput with:

`sudo apt-get install python-uinput`

I got this error:   

> E: Unable to locate package python-uinput

After this i cloned the git-rep:

`git clone -v https://github.com/tuomasjjrasanen/python-uinput.git`

Then i run  `python setup.py build` and `python setup.py install`

No problems, i've copied the `40-uinput.rules` to `/etc/udev/rules.d/`
and edited it to:

`ACTION=="add|change", KERNEL=="event[0-9]*", ENV{ID_VENDOR_ID}=="012a", ENV{ID_MODEL_ID}=="034b",
ENV{ID_INPUT_KEYBOARD}="1", ENV{ID_INPUT_TABLET}="1"SUBSYSTEM=="input", ATTRS{name}=="python-uinput",
ENV{ID_INPUT_KEYBOARD}="1"KERNEL=="uinput", MODE:="0666" `

Then i've downloaded your file with 

`wget https://github.com/dillbyrne/es-cec-input/blob/master/es-cec-input.py`

changed chmod to u+x and tried to launch and i get this error:
 

> pi@retropie:~/pythonUinput $ ./es-cec-input.py
> ./es-cec-input.py: line 1: syntax error near unexpected token `newline'
> ./es-cec-input.py: line 1: `<!DOCTYPE html>'

I really don't know what i can do to fix it.
I hope you can help me.

c4sti3l

**Comment by dillbyrne** [comment]
Your wget command downloaded the webpage displaying the script with syntax highlighting for viewing the code, not the raw script itself. Use this url instead

https://raw.githubusercontent.com/dillbyrne/es-cec-input/master/es-cec-input.py
