### ISSUE TITLE
Missing 40-uinput.rules file

### ISSUE THREAD

**Issue by citaria** [dillbyrne/es-cec-input#13]
Hello there,
    I’m a newb admittingly and I’ve been trying to get this to work for a while.

I’ve installed the cec-utils package and also the python-uinput package but there is no 40-uinput.rules file at:
/etc/udev/rules.d/

Is this supposed to be there upon install of the above packages?  Do I simply need to create it?

**Comment by Jademalo** [comment]
It was missing for me too, but after creating it myself everything seems to be working fine.

**Comment by dillbyrne** [comment]
Hi @citaria. Yes create it if it was not created automatically by the package. If after creating it, with the expected values listed in the read me, you are still having problems feel free to open a new issue.
