### ISSUE TITLE
Retroarch.cfg

### ISSUE THREAD

**Issue by deep8787** [dillbyrne/es-cec-input#27]
Raspberry Pi 4b 2gb
Retropie 4.8 (original image used)

Hi all,

I am trying to get this working since I would love to just use my remote to start kodi instead of needing my controller or mini keyboard. Ive installed the dependencies and I get to the part to try the script, when executing the script I end up with an output that states:

```
The 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul', 'nul' (not sure how many but a lot of them lol) keys in your retroarch.cfg are unsupported by this script.

Supported keys are:
bla bla blaaa etc
```

Now my question is, is it the config file in opt/configs/all/retroarch.cfg? All the players input are set to nul. 

As far as I understand, retroarch pulls the data from the joypad config files.
My keyboard has been configured, Ive done some reboots inbetween too. I dont see a keyboard config file where all the joypad configs are stored.

Could someone hopefully shed some light on what I am doing wrong.

Thank you!

**Comment by deep8787** [comment]
OK I had a closer look at my retroarch.cfg and i see entries referring to my keyboard, e.g.:

input_player1_down = "down"
input_player1_b = "enter"
input_player1_l = "q"
input_player1_l2 = "r"

etc

So I assumed it should work. Any thoughts?

**Comment by deep8787** [comment]
OK I tinkered with the es-cec-input.py and made some progress. 

I made a slight change so that the config is read from a file called cec.cfg which resides in my home directory and I copied the input info from retroarch.cfg into it. **Line 92** reads now *key_bindings = get_key_bindings('/home/pi/cec.cfg')*

When I run the py script now, it reads the value from the new cec.cfg BUT for some reason I cannot get them to accept the values as I get this output now:


*The 'del"', 'enter"', 'down"', 'q"', 'r"', 'y"', 'left"', 'e"', 't"', 'u"', 'right"', 'backquote"', 'escape"', 'up"', 'w"', '' keys in your retroarch.cfg are unsupported                by this script*

that " shouldnt be there with each entry, im not sure why it is. I tried rewriting it, it seems to persist. Help! :D

**Comment by deep8787** [comment]
OK....some more progress.

I have tinkered with this *keys.append(line.split('=')[1][2:-2])* on **Line 123** as that is what seems to be reading my values incorrectly....

I changed it to *keys.append(line.split('"')[-2])* and when I run the script, no more error and I can press buttons and I see its working as the command line is writing stuff as I press buttons, but I have to CTRL+C to cancel the script. Not sure if thats normal or not. 

Regardless, so I added it to autostart.sh (with an & at the end so it runs in the background) and rebooted...its receiving the input on emulationstation but pressing down on my remote now works as Select for some reason. All the mapping just seems wonkey.

I am gettin there slowly tho :D

**Comment by deep8787** [comment]
Woohoo, i got it working. well enough for me anyways :D I just wanted the arrows, select and back to work so I can navigate emulationstation.
In order for me to get it working in the end, I had to make 2 edits to the py script:

Line 92: key_bindings = get_key_bindings('/home/pi/cec.cfg')
Line 123: keys.append(line.split('=')[1][2:-2])

Create the cec.cfg in the home directory and the order of the list was very specific, it had to be in this exact order:

*input_player1_a = "del"
input_player1_b = "enter"
input_player1_r = "e"
input_player1_r2 = "t"
input_player1_l3 = "y"
#input_player1_analog_dpad_mode = "0"
input_player1_l2 = "r"
input_player1_select = "backquote"
#input_player1_joypad_index = "0"
input_player1_l = "q"
input_player1_left = "left"
input_player1_right = "right"
#input_player1_mouse_index = "0"
input_player1_up = "up"
input_player1_down = "down"
input_player1_r3 = "u"
input_player1_start = "escape"
input_player1_x = "w"
input_player1_y = "a"*

And to make it start up I edited autostart.sh (im using retropie image, you can also use cron or systemd)  by adding in the script:
*/home/pi/es-cec-input.py &* 
in the line above *emulationstation #auto*
to make the script start before emulationstation, pretty self explanatory really :)

And reboot!

I am done! Hopefully this might help someone in the future also wanting to do the same.

**Comment by dillbyrne** [comment]
H @deep8787 i, Sorry I'm late getting back to you I was on vacation. Glad you got it sorted. I don't have a pi4 nor a newer version of retropie running anymore to test this, but I'm happy to answer any questions. 

Thanks for posting your solution :+1:  .

I'll close this for now as you seem to have sorted it but feel free to reopen it if you need to
