### ISSUE TITLE
'nte' key unsupported

### ISSUE THREAD

**Issue by wonx** [dillbyrne/es-cec-input#3]
Hi,

I tried your script, in order to be able to use my remote with the emulationstation interface. When I run it, I get this message:

`The 'nte' key in your retroarch.cfg is unsupported by this script`
And then a list of the supported keys.

The thing is: what key is that? In which retroarch.cfg (if I search in my filesystem, there are several of them. I assume is the one located at /opt/retropie/configs/all/retroarch.cfg). In that file there was no reference to an "nte" key whatsoever.

I can't figure it out what it means.

...help?

**Comment by dillbyrne** [comment]
Hi @wonx can you post your /opt/retropie/configs/all/retroarch.cfg here ?

The script prints unsupported keys as an exception so it could be catching another error in the catch block here and printing that. I'll try it with your retroarch config and see if I can find the source of it.


Also what version of retropie are you running it on and what OS ?

**Comment by wonx** [comment]
Hi again @dillbyrne,

Here's my retroarch config file (I added ".txt" to the extension in order to be able to upload it here):

[retroarch.cfg.txt](https://github.com/dillbyrne/es-cec-input/files/770858/retroarch.cfg.txt)

About my retropie version... that's a tough question. I was using Retropie 3.0 image but I regularly use the retropie setup script in order to update some of its components, including the said retropie script, emulationstation, retroarch, kodi, ps3 gamepad drivers and a few emulators. I also upgraded debian from wheezy to jessie. Everything works just fine, and I have a few personalizations I wouldn't like to lose if I did a fresh install. Tell me if I need to upgrade any particular component or you need know the version.

**Comment by dillbyrne** [comment]
I was able to reproduce the issue. It is due to not having the values on right of the equals in quotes. In retropie version 4.1 the values are automatically put in quotes so `nte` was enter getting incorrectly trimmed due to the lack of quotes.

I could add some code in to account for this but the reason is due to the legacy config for retropie 3. In 4 it has the quotes in the config by default. Given that most people will be using 4 and the fix is easy enough I don't see the point in adding it in for the legacy config.

if you do not wish to use quotes in the RA config you can change the line
` keys.append(line.split('=')[1][2:-2])` to ` keys.append(line.split('=')[1][1:-1])`
 and it will work. I would try adding quotes first however

The format for retropie 4+ is a space after the = and quotes wrapping the values
```
input_player1_a = "a"
input_player1_b = "b"
input_player1_y = "y"
input_player1_x = "x"
input_player1_start = "d"
input_player1_select = "s"
input_player1_l = "shift"
input_player1_r = "rshift"
input_player1_left = "left"
input_player1_right = "right"
input_player1_up = "up"
input_player1_down = "down"
input_player1_l2 = "ctrl"
input_player1_r2 = "rctrl"
input_player1_l3 = "num1"
input_player1_r3 = "num2"
```

**Comment by dillbyrne** [comment]
Also if you do not plan on using a button be sure to comment it out as the script will try to parse it as a key and will throw an error as an empty string is not a valid key. It is better to not have any blank values at all as the script uses offsets for the buttons. 0 for a ,1 for b , 2 for y and so on

```
input_player1_a = "enter"
input_player1_b = "backspace"
input_player1_y = "escape"
input_player1_x = "ctrl"
input_player1_start = "tab"
# input_player1_select = 
input_player1_l = "alt"
input_player1_r = "num3"
input_player1_left = "left"
input_player1_right = "right"
input_player1_up = "up"
input_player1_down = "down"
# input_player1_l2 = 
# input_player1_r2 = 
# input_player1_l3 = 

```

**Comment by wonx** [comment]
I will try it this afternoon. I agree, it makes no sense to change the script if newer retropie versions use the "quoted" format. 

Thank you very much!

**Comment by dillbyrne** [comment]
No problem. if you are still having problems after you try the above feel free to reopen the issue.
