### ISSUE TITLE
Problem when exiting Kodi and returning to Emulationstation

### ISSUE THREAD

**Issue by yukiob** [dillbyrne/es-cec-input#5]
Thanks for making CEC work in Emulationstation. I have one small issue though.
Everything works fine until I exit Kodi and return to Emulationstation. Then I get no response from CEC remote. If I start the script again it works, but is there some way to make sure it is always running?

**Comment by dillbyrne** [comment]
Hi @yukiob. Try the solution outlined in #2 where another user had the same issue . There should be a setting in kodi that takes care of it.

**Comment by yukiob** [comment]
Thanks for quick reply. I tried the settings suggested in #2  but I still get no response from CEC remote when returning to Emulationstation.

**Comment by dillbyrne** [comment]
If you have access to a terminal can you run `ps aux | grep es-cec` after exiting kodi to see if the script is still running ?

If it is running initially before you start kodi then it is likely to be a kodi setting. Can you list your kodi input adapter settings  on the expert level ?

**Comment by dillbyrne** [comment]
Did you try changing "Send inactive source command on shutdown" to disabled ? . Also have a look at your tv settings and see if there is any options related to cec

**Comment by dillbyrne** [comment]
Closing as there was no reply. feel free to reopen if issue persists

**Comment by donders** [comment]
@dillbyrne if you are still at all familiar enough to provide help, this is happening to me on 2 different setups. I notice when I start kodi from commandline, that this script seems to feedback remote inputs to the commandline while Kodi is running, so at least that's good I guess.

I haven't checked the TV's CEC settings, I'll check that first before coming back here.
